// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: protos/jobs.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobCreateRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JobName        string                 `protobuf:"bytes,1,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	JobDescription string                 `protobuf:"bytes,2,opt,name=job_description,json=jobDescription,proto3" json:"job_description,omitempty"`
	Status         string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *JobCreateRequest) Reset() {
	*x = JobCreateRequest{}
	mi := &file_protos_jobs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobCreateRequest) ProtoMessage() {}

func (x *JobCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_jobs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobCreateRequest.ProtoReflect.Descriptor instead.
func (*JobCreateRequest) Descriptor() ([]byte, []int) {
	return file_protos_jobs_proto_rawDescGZIP(), []int{0}
}

func (x *JobCreateRequest) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *JobCreateRequest) GetJobDescription() string {
	if x != nil {
		return x.JobDescription
	}
	return ""
}

func (x *JobCreateRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type JobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobRequest) Reset() {
	*x = JobRequest{}
	mi := &file_protos_jobs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobRequest) ProtoMessage() {}

func (x *JobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_jobs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobRequest.ProtoReflect.Descriptor instead.
func (*JobRequest) Descriptor() ([]byte, []int) {
	return file_protos_jobs_proto_rawDescGZIP(), []int{1}
}

func (x *JobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type JobResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JobId          string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	JobName        string                 `protobuf:"bytes,2,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	JobDescription string                 `protobuf:"bytes,3,opt,name=job_description,json=jobDescription,proto3" json:"job_description,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *JobResponse) Reset() {
	*x = JobResponse{}
	mi := &file_protos_jobs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobResponse) ProtoMessage() {}

func (x *JobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_jobs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobResponse.ProtoReflect.Descriptor instead.
func (*JobResponse) Descriptor() ([]byte, []int) {
	return file_protos_jobs_proto_rawDescGZIP(), []int{2}
}

func (x *JobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobResponse) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *JobResponse) GetJobDescription() string {
	if x != nil {
		return x.JobDescription
	}
	return ""
}

func (x *JobResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type JobListOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobListOptions) Reset() {
	*x = JobListOptions{}
	mi := &file_protos_jobs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobListOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobListOptions) ProtoMessage() {}

func (x *JobListOptions) ProtoReflect() protoreflect.Message {
	mi := &file_protos_jobs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobListOptions.ProtoReflect.Descriptor instead.
func (*JobListOptions) Descriptor() ([]byte, []int) {
	return file_protos_jobs_proto_rawDescGZIP(), []int{3}
}

func (x *JobListOptions) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_protos_jobs_proto protoreflect.FileDescriptor

const file_protos_jobs_proto_rawDesc = "" +
	"\n" +
	"\x11protos/jobs.proto\x12\fgrpc.jobs.v1\x1a\x1bgoogle/protobuf/empty.proto\"n\n" +
	"\x10JobCreateRequest\x12\x19\n" +
	"\bjob_name\x18\x01 \x01(\tR\ajobName\x12'\n" +
	"\x0fjob_description\x18\x02 \x01(\tR\x0ejobDescription\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"#\n" +
	"\n" +
	"JobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\x80\x01\n" +
	"\vJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x19\n" +
	"\bjob_name\x18\x02 \x01(\tR\ajobName\x12'\n" +
	"\x0fjob_description\x18\x03 \x01(\tR\x0ejobDescription\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"&\n" +
	"\x0eJobListOptions\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit2\x92\x02\n" +
	"\x04Jobs\x12F\n" +
	"\tCreateJob\x12\x1e.grpc.jobs.v1.JobCreateRequest\x1a\x19.grpc.jobs.v1.JobResponse\x12=\n" +
	"\x06GetJob\x12\x18.grpc.jobs.v1.JobRequest\x1a\x19.grpc.jobs.v1.JobResponse\x12D\n" +
	"\aGetJobs\x12\x1c.grpc.jobs.v1.JobListOptions\x1a\x19.grpc.jobs.v1.JobResponse0\x01\x12=\n" +
	"\tDeleteJob\x12\x18.grpc.jobs.v1.JobRequest\x1a\x16.google.protobuf.EmptyBKZ1github.com/chrishenyard/grpc_api_go/protos;protos\xaa\x02\x15Grpc.Service.Servicesb\x06proto3"

var (
	file_protos_jobs_proto_rawDescOnce sync.Once
	file_protos_jobs_proto_rawDescData []byte
)

func file_protos_jobs_proto_rawDescGZIP() []byte {
	file_protos_jobs_proto_rawDescOnce.Do(func() {
		file_protos_jobs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_jobs_proto_rawDesc), len(file_protos_jobs_proto_rawDesc)))
	})
	return file_protos_jobs_proto_rawDescData
}

var file_protos_jobs_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protos_jobs_proto_goTypes = []any{
	(*JobCreateRequest)(nil), // 0: grpc.jobs.v1.JobCreateRequest
	(*JobRequest)(nil),       // 1: grpc.jobs.v1.JobRequest
	(*JobResponse)(nil),      // 2: grpc.jobs.v1.JobResponse
	(*JobListOptions)(nil),   // 3: grpc.jobs.v1.JobListOptions
	(*emptypb.Empty)(nil),    // 4: google.protobuf.Empty
}
var file_protos_jobs_proto_depIdxs = []int32{
	0, // 0: grpc.jobs.v1.Jobs.CreateJob:input_type -> grpc.jobs.v1.JobCreateRequest
	1, // 1: grpc.jobs.v1.Jobs.GetJob:input_type -> grpc.jobs.v1.JobRequest
	3, // 2: grpc.jobs.v1.Jobs.GetJobs:input_type -> grpc.jobs.v1.JobListOptions
	1, // 3: grpc.jobs.v1.Jobs.DeleteJob:input_type -> grpc.jobs.v1.JobRequest
	2, // 4: grpc.jobs.v1.Jobs.CreateJob:output_type -> grpc.jobs.v1.JobResponse
	2, // 5: grpc.jobs.v1.Jobs.GetJob:output_type -> grpc.jobs.v1.JobResponse
	2, // 6: grpc.jobs.v1.Jobs.GetJobs:output_type -> grpc.jobs.v1.JobResponse
	4, // 7: grpc.jobs.v1.Jobs.DeleteJob:output_type -> google.protobuf.Empty
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_jobs_proto_init() }
func file_protos_jobs_proto_init() {
	if File_protos_jobs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_jobs_proto_rawDesc), len(file_protos_jobs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_jobs_proto_goTypes,
		DependencyIndexes: file_protos_jobs_proto_depIdxs,
		MessageInfos:      file_protos_jobs_proto_msgTypes,
	}.Build()
	File_protos_jobs_proto = out.File
	file_protos_jobs_proto_goTypes = nil
	file_protos_jobs_proto_depIdxs = nil
}
